version: '3.4'

services:
  db:
    image: postgres
    volumes:
      - ./docker/dataPostgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES="desafio_dev","desafio_dev_test"  
      - POSTGRES_USER=desafio_dev
      - POSTGRES_PASSWORD=desafio_dev
    ports:
      - 54321:5432
  redis:
    image: redis
    ports:
      - "6379:6379"    
  # api:
  #   build: ./backend
  #   environment: 
  #     - ProjectManagerContextDb=Host=db;Port=5432;Database=projectmanager;Username=projectmanager;Password=projectmanager
  #   ports:
  #     - 5002:80
  #   links:
  #     - db
  #   depends_on:
  #     - db

  # web:
  #   build: ./frontend
  #   volumes:
  #     - ./docker/nginx/:/etc/nginx/conf.d
  #   ports:
  #     - 7070:80
  #   depends_on:
  #     - api